[package]
name = "year_2024"
version = "0.1.0"
edition = "2021"

[dependencies]
colored = "2.1.0"
colour = "2.1.0"
humantime = "2.1.0"
term_size = "0.3.2"

[[bin]]
name = "year_2024"
path = "main.rs"
