[package]
name = "year_2024"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.21", features = ["cargo"] }
colored = "2.1.0"
image = "0.25.5"
regex = "1.11.1"
term_size = "0.3.2"

[[bin]]
name = "year_2024"
path = "main.rs"
